name: Test

on:
  pull_request:
    branches:
      - "main"

jobs:
  check-diff:
    name: Check diff size
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Check that diff isn't too small"
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          FILES_CHANGED=$(gh pr diff ${{github.event.pull_request.number}} --name-only | wc -l)
          echo "Number of files changed in this PR: ${FILES_CHANGED}"
          if [ $FILES_CHANGED -gte 5 ]
          then
            echo "You've updated at least some files good work! 😎"
            exit 1
          else 
            echo "Looks like you've not completed enough of the exercises"
            exit 0
          fi
